/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as CardsRouteImport } from "./routes/cards"
import { Route as DecklistsRouteImport } from "./routes/decklists"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as AdminUsersRouteImport } from "./routes/admin/users"
import { Route as DecksIndexRouteImport } from "./routes/decks.index"
import { Route as DecksDeckIdRouteImport } from "./routes/decks.$deckId"
import { Route as GamesIndexRouteImport } from "./routes/games.index"
import { Route as GamesGameIdRouteImport } from "./routes/games.$gameId"
import { Route as GamesNewRouteImport } from "./routes/games.new"
import { Route as PlayersIndexRouteImport } from "./routes/players.index"
import { Route as PlayersPlayerIdRouteImport } from "./routes/players.$playerId"
import { Route as GamesGameIdEditRouteImport } from "./routes/games.$gameId_.edit"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: "/cards",
  path: "/cards",
  getParentRoute: () => rootRouteImport,
} as any)
const DecklistsRoute = DecklistsRouteImport.update({
  id: "/decklists",
  path: "/decklists",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/admin/users",
  path: "/admin/users",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: "/decks/",
  path: "/decks/",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: "/decks/$deckId",
  path: "/decks/$deckId",
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: "/games/",
  path: "/games/",
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: "/games/$gameId",
  path: "/games/$gameId",
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: "/games/new",
  path: "/games/new",
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: "/players/",
  path: "/players/",
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: "/players/$playerId",
  path: "/players/$playerId",
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdEditRoute = GamesGameIdEditRouteImport.update({
  id: "/games/$gameId_/edit",
  path: "/games/$gameId/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/cards": typeof CardsRoute
  "/decklists": typeof DecklistsRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/settings": typeof SettingsRoute
  "/admin/users": typeof AdminUsersRoute
  "/decks/$deckId": typeof DecksDeckIdRoute
  "/games/$gameId": typeof GamesGameIdRoute
  "/games/new": typeof GamesNewRoute
  "/players/$playerId": typeof PlayersPlayerIdRoute
  "/decks/": typeof DecksIndexRoute
  "/games/": typeof GamesIndexRoute
  "/players/": typeof PlayersIndexRoute
  "/games/$gameId/edit": typeof GamesGameIdEditRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/cards": typeof CardsRoute
  "/decklists": typeof DecklistsRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/settings": typeof SettingsRoute
  "/admin/users": typeof AdminUsersRoute
  "/decks/$deckId": typeof DecksDeckIdRoute
  "/games/$gameId": typeof GamesGameIdRoute
  "/games/new": typeof GamesNewRoute
  "/players/$playerId": typeof PlayersPlayerIdRoute
  "/decks": typeof DecksIndexRoute
  "/games": typeof GamesIndexRoute
  "/players": typeof PlayersIndexRoute
  "/games/$gameId/edit": typeof GamesGameIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/cards": typeof CardsRoute
  "/decklists": typeof DecklistsRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/settings": typeof SettingsRoute
  "/admin/users": typeof AdminUsersRoute
  "/decks/$deckId": typeof DecksDeckIdRoute
  "/games/$gameId": typeof GamesGameIdRoute
  "/games/new": typeof GamesNewRoute
  "/players/$playerId": typeof PlayersPlayerIdRoute
  "/decks/": typeof DecksIndexRoute
  "/games/": typeof GamesIndexRoute
  "/players/": typeof PlayersIndexRoute
  "/games/$gameId_/edit": typeof GamesGameIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/cards"
    | "/decklists"
    | "/login"
    | "/register"
    | "/settings"
    | "/admin/users"
    | "/decks/$deckId"
    | "/games/$gameId"
    | "/games/new"
    | "/players/$playerId"
    | "/decks/"
    | "/games/"
    | "/players/"
    | "/games/$gameId/edit"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/cards"
    | "/decklists"
    | "/login"
    | "/register"
    | "/settings"
    | "/admin/users"
    | "/decks/$deckId"
    | "/games/$gameId"
    | "/games/new"
    | "/players/$playerId"
    | "/decks"
    | "/games"
    | "/players"
    | "/games/$gameId/edit"
  id:
    | "__root__"
    | "/"
    | "/cards"
    | "/decklists"
    | "/login"
    | "/register"
    | "/settings"
    | "/admin/users"
    | "/decks/$deckId"
    | "/games/$gameId"
    | "/games/new"
    | "/players/$playerId"
    | "/decks/"
    | "/games/"
    | "/players/"
    | "/games/$gameId_/edit"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  DecklistsRoute: typeof DecklistsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesNewRoute: typeof GamesNewRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  DecksIndexRoute: typeof DecksIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  GamesGameIdEditRoute: typeof GamesGameIdEditRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cards": {
      id: "/cards"
      path: "/cards"
      fullPath: "/cards"
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decklists": {
      id: "/decklists"
      path: "/decklists"
      fullPath: "/decklists"
      preLoaderRoute: typeof DecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/admin/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks/": {
      id: "/decks/"
      path: "/decks"
      fullPath: "/decks/"
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks/$deckId": {
      id: "/decks/$deckId"
      path: "/decks/$deckId"
      fullPath: "/decks/$deckId"
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/games/": {
      id: "/games/"
      path: "/games"
      fullPath: "/games/"
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/games/$gameId": {
      id: "/games/$gameId"
      path: "/games/$gameId"
      fullPath: "/games/$gameId"
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/games/new": {
      id: "/games/new"
      path: "/games/new"
      fullPath: "/games/new"
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/players/": {
      id: "/players/"
      path: "/players"
      fullPath: "/players/"
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/players/$playerId": {
      id: "/players/$playerId"
      path: "/players/$playerId"
      fullPath: "/players/$playerId"
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/games/$gameId_/edit": {
      id: "/games/$gameId_/edit"
      path: "/games/$gameId/edit"
      fullPath: "/games/$gameId/edit"
      preLoaderRoute: typeof GamesGameIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  DecklistsRoute: DecklistsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DecksDeckIdRoute: DecksDeckIdRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GamesNewRoute: GamesNewRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  DecksIndexRoute: DecksIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  GamesGameIdEditRoute: GamesGameIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
