/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as ImportRouteImport } from "./routes/import"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as AdminCatalogRouteImport } from "./routes/admin/catalog"
import { Route as AdminDiscordRouteImport } from "./routes/admin/discord"
import { Route as AdminSettingsRouteImport } from "./routes/admin/settings"
import { Route as AdminUsersRouteImport } from "./routes/admin/users"
import { Route as CommandersIndexRouteImport } from "./routes/commanders.index"
import { Route as CommandersCommanderIdRouteImport } from "./routes/commanders.$commanderId"
import { Route as DecksIndexRouteImport } from "./routes/decks.index"
import { Route as DecksDeckIdRouteImport } from "./routes/decks.$deckId"
import { Route as DecksChooseRouteImport } from "./routes/decks.choose"
import { Route as GamesIndexRouteImport } from "./routes/games.index"
import { Route as GamesGameIdRouteImport } from "./routes/games.$gameId"
import { Route as GamesNewRouteImport } from "./routes/games.new"
import { Route as PlayersIndexRouteImport } from "./routes/players.index"
import { Route as PlayersPlayerIdRouteImport } from "./routes/players.$playerId"
import { Route as GamesGameIdEditRouteImport } from "./routes/games.$gameId_.edit"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: "/import",
  path: "/import",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: "/catalog",
  path: "/catalog",
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscordRoute = AdminDiscordRouteImport.update({
  id: "/discord",
  path: "/discord",
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any)
const CommandersIndexRoute = CommandersIndexRouteImport.update({
  id: "/commanders/",
  path: "/commanders/",
  getParentRoute: () => rootRouteImport,
} as any)
const CommandersCommanderIdRoute = CommandersCommanderIdRouteImport.update({
  id: "/commanders/$commanderId",
  path: "/commanders/$commanderId",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: "/decks/",
  path: "/decks/",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: "/decks/$deckId",
  path: "/decks/$deckId",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksChooseRoute = DecksChooseRouteImport.update({
  id: "/decks/choose",
  path: "/decks/choose",
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: "/games/",
  path: "/games/",
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: "/games/$gameId",
  path: "/games/$gameId",
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: "/games/new",
  path: "/games/new",
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: "/players/",
  path: "/players/",
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: "/players/$playerId",
  path: "/players/$playerId",
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdEditRoute = GamesGameIdEditRouteImport.update({
  id: "/games/$gameId_/edit",
  path: "/games/$gameId/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/import": typeof ImportRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/settings": typeof SettingsRoute
  "/admin/catalog": typeof AdminCatalogRoute
  "/admin/discord": typeof AdminDiscordRoute
  "/admin/settings": typeof AdminSettingsRoute
  "/admin/users": typeof AdminUsersRoute
  "/commanders/$commanderId": typeof CommandersCommanderIdRoute
  "/decks/$deckId": typeof DecksDeckIdRoute
  "/decks/choose": typeof DecksChooseRoute
  "/games/$gameId": typeof GamesGameIdRoute
  "/games/new": typeof GamesNewRoute
  "/players/$playerId": typeof PlayersPlayerIdRoute
  "/commanders/": typeof CommandersIndexRoute
  "/decks/": typeof DecksIndexRoute
  "/games/": typeof GamesIndexRoute
  "/players/": typeof PlayersIndexRoute
  "/games/$gameId/edit": typeof GamesGameIdEditRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/import": typeof ImportRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/settings": typeof SettingsRoute
  "/admin/catalog": typeof AdminCatalogRoute
  "/admin/discord": typeof AdminDiscordRoute
  "/admin/settings": typeof AdminSettingsRoute
  "/admin/users": typeof AdminUsersRoute
  "/commanders/$commanderId": typeof CommandersCommanderIdRoute
  "/decks/$deckId": typeof DecksDeckIdRoute
  "/decks/choose": typeof DecksChooseRoute
  "/games/$gameId": typeof GamesGameIdRoute
  "/games/new": typeof GamesNewRoute
  "/players/$playerId": typeof PlayersPlayerIdRoute
  "/commanders": typeof CommandersIndexRoute
  "/decks": typeof DecksIndexRoute
  "/games": typeof GamesIndexRoute
  "/players": typeof PlayersIndexRoute
  "/games/$gameId/edit": typeof GamesGameIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/import": typeof ImportRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/settings": typeof SettingsRoute
  "/admin/catalog": typeof AdminCatalogRoute
  "/admin/discord": typeof AdminDiscordRoute
  "/admin/settings": typeof AdminSettingsRoute
  "/admin/users": typeof AdminUsersRoute
  "/commanders/$commanderId": typeof CommandersCommanderIdRoute
  "/decks/$deckId": typeof DecksDeckIdRoute
  "/decks/choose": typeof DecksChooseRoute
  "/games/$gameId": typeof GamesGameIdRoute
  "/games/new": typeof GamesNewRoute
  "/players/$playerId": typeof PlayersPlayerIdRoute
  "/commanders/": typeof CommandersIndexRoute
  "/decks/": typeof DecksIndexRoute
  "/games/": typeof GamesIndexRoute
  "/players/": typeof PlayersIndexRoute
  "/games/$gameId_/edit": typeof GamesGameIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/import"
    | "/login"
    | "/register"
    | "/settings"
    | "/admin/catalog"
    | "/admin/discord"
    | "/admin/settings"
    | "/admin/users"
    | "/commanders/$commanderId"
    | "/decks/$deckId"
    | "/decks/choose"
    | "/games/$gameId"
    | "/games/new"
    | "/players/$playerId"
    | "/commanders/"
    | "/decks/"
    | "/games/"
    | "/players/"
    | "/games/$gameId/edit"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/admin"
    | "/import"
    | "/login"
    | "/register"
    | "/settings"
    | "/admin/catalog"
    | "/admin/discord"
    | "/admin/settings"
    | "/admin/users"
    | "/commanders/$commanderId"
    | "/decks/$deckId"
    | "/decks/choose"
    | "/games/$gameId"
    | "/games/new"
    | "/players/$playerId"
    | "/commanders"
    | "/decks"
    | "/games"
    | "/players"
    | "/games/$gameId/edit"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/import"
    | "/login"
    | "/register"
    | "/settings"
    | "/admin/catalog"
    | "/admin/discord"
    | "/admin/settings"
    | "/admin/users"
    | "/commanders/$commanderId"
    | "/decks/$deckId"
    | "/decks/choose"
    | "/games/$gameId"
    | "/games/new"
    | "/players/$playerId"
    | "/commanders/"
    | "/decks/"
    | "/games/"
    | "/players/"
    | "/games/$gameId_/edit"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  CommandersCommanderIdRoute: typeof CommandersCommanderIdRoute
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  DecksChooseRoute: typeof DecksChooseRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesNewRoute: typeof GamesNewRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  CommandersIndexRoute: typeof CommandersIndexRoute
  DecksIndexRoute: typeof DecksIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  GamesGameIdEditRoute: typeof GamesGameIdEditRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/import": {
      id: "/import"
      path: "/import"
      fullPath: "/import"
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/catalog": {
      id: "/admin/catalog"
      path: "/catalog"
      fullPath: "/admin/catalog"
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/discord": {
      id: "/admin/discord"
      path: "/discord"
      fullPath: "/admin/discord"
      preLoaderRoute: typeof AdminDiscordRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/settings": {
      id: "/admin/settings"
      path: "/settings"
      fullPath: "/admin/settings"
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/commanders/": {
      id: "/commanders/"
      path: "/commanders"
      fullPath: "/commanders/"
      preLoaderRoute: typeof CommandersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/commanders/$commanderId": {
      id: "/commanders/$commanderId"
      path: "/commanders/$commanderId"
      fullPath: "/commanders/$commanderId"
      preLoaderRoute: typeof CommandersCommanderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks/": {
      id: "/decks/"
      path: "/decks"
      fullPath: "/decks/"
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks/$deckId": {
      id: "/decks/$deckId"
      path: "/decks/$deckId"
      fullPath: "/decks/$deckId"
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks/choose": {
      id: "/decks/choose"
      path: "/decks/choose"
      fullPath: "/decks/choose"
      preLoaderRoute: typeof DecksChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/games/": {
      id: "/games/"
      path: "/games"
      fullPath: "/games/"
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/games/$gameId": {
      id: "/games/$gameId"
      path: "/games/$gameId"
      fullPath: "/games/$gameId"
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/games/new": {
      id: "/games/new"
      path: "/games/new"
      fullPath: "/games/new"
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/players/": {
      id: "/players/"
      path: "/players"
      fullPath: "/players/"
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/players/$playerId": {
      id: "/players/$playerId"
      path: "/players/$playerId"
      fullPath: "/players/$playerId"
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/games/$gameId_/edit": {
      id: "/games/$gameId_/edit"
      path: "/games/$gameId/edit"
      fullPath: "/games/$gameId/edit"
      preLoaderRoute: typeof GamesGameIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminDiscordRoute: typeof AdminDiscordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminDiscordRoute: AdminDiscordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  CommandersCommanderIdRoute: CommandersCommanderIdRoute,
  DecksDeckIdRoute: DecksDeckIdRoute,
  DecksChooseRoute: DecksChooseRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GamesNewRoute: GamesNewRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  CommandersIndexRoute: CommandersIndexRoute,
  DecksIndexRoute: DecksIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  GamesGameIdEditRoute: GamesGameIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
