defmodule TheGatheringWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :the_gathering

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_the_gathering_key",
    signing_salt: "sQwWhYdP",
    same_site: "Lax"
  ]

  # The largest legitimate client frame is a WebRTC signal, capped at 64 KB by
  # WebcamTableChannel; leave headroom for the envelope and JSON escaping.
  socket "/socket", TheGatheringWeb.UserSocket,
    websocket: [max_frame_size: 131_072],
    longpoll: false

  # Vite output (hashed filenames) is safe to cache forever.
  plug Plug.Static,
    at: "/assets/react",
    from: {:the_gathering, "priv/static/assets/react"},
    gzip: not code_reloading?,
    cache_control_for_etags: "public, max-age=31536000, immutable"

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :the_gathering,
    gzip: not code_reloading?,
    only: TheGatheringWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :the_gathering
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TheGatheringWeb.Router
end
