defmodule TheGatheringWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :the_gathering

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # Without :max_age the browser drops the cookie when it closes, so members had
  # to sign in again far sooner than the 14-day server-side token allows. Match
  # UserToken's session validity; UserAuth reissues the token (and cookie) after
  # 7 days, so active members stay signed in indefinitely.
  @session_options [
    store: :cookie,
    key: "_the_gathering_key",
    signing_salt: "sQwWhYdP",
    same_site: "Lax",
    max_age: 60 * 60 * 24 * 14
  ]

  # The largest legitimate client frame is a relayed card crop (`peer_message`), capped at
  # 256 KiB by WebcamTableChannel; leave headroom for the envelope and JSON escaping.
  socket "/socket", TheGatheringWeb.UserSocket,
    websocket: [max_frame_size: 393_216],
    longpoll: false

  # Vite output (hashed filenames) is safe to cache forever. COEP lets the recognizer worker
  # and onnxruntime's pthread workers start inside the cross-origin-isolated webcam table
  # (a dedicated worker in an isolated document must itself be served with COEP).
  plug Plug.Static,
    at: "/assets/react",
    from: {:the_gathering, "priv/static/assets/react"},
    gzip: not code_reloading?,
    cache_control_for_etags: "public, max-age=31536000, immutable",
    headers: %{"cross-origin-embedder-policy" => "require-corp"}

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :the_gathering,
    gzip: not code_reloading?,
    only: TheGatheringWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :the_gathering
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TheGatheringWeb.Router
end
