import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :the_gathering, TheGatheringWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# TLS termination is left to the reverse proxy in front of the container, which
# is the norm for self-hosted deployments. Plain HTTP on a LAN must keep working.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
